#ภารกิจที่ 5
first_number = input('input first number : ')
second_number = input('input second number :')
third_number = input('input third number :')
fourth_number = input('input fourth number :')
fifth_number = input('input fifth number :')
print("float of " +first_number+ " is ",float(first_number))
print("complex of " +first_number+ " is ",complex(first_number))
print("float of " +second_number+ " is  ",float(second_number))
print("complex of " +second_number+ " is ",complex(second_number))
print("float of " +third_number+ " is  ",float(third_number))
print("complex of " +third_number+ " is  ",complex(third_number))
print("float of " +fourth_number+ " is  ",float(fourth_number))
print("complex of " +fourth_number+ " is  ",complex(fourth_number))
print("float of " +fifth_number+ " is  ",float(fifth_number))
print("complex of " +fifth_number+ " is  ",complex(fifth_number))