x = """Is the "big, beautiful" India-US trade deal slipping out of reach?
With just days to go before a 9 July deadline set by US President Donald Trump's administration, hopes of clinching an interim trade pact between Delhi and Washington remain alive but increasingly entangled in hard bargaining.
Despite White House Press Secretary Karoline Leavitt hinting that the deal was imminent, and Indian Finance Minister Nirmala Sitharaman's upbeat assertion that Delhi would welcome "a big, good, beautiful" agreement - in response to Trump's claim that a trade deal with Delhi is coming and would "open up" the Indian market - negotiators remain locked in tough discussions.
Key sticking points persist, particularly over agricultural access, auto components and tariffs on Indian steel
Indian trade officials have extended their stay in Washington for another round of talks, even as Delhi signals "very big red lines" on farm and dairy protections, and the US presses for wider market openings. The tone remains optimistic - but the window to strike a deal appears to be narrowing.
Trump wants India to buy US corn - but here's why it probably won
"The next seven days could determine whether India and the US settle for a limited 'mini-deal' or walk away from the negotiating table - at least for now," says Ajay Srivastava, a former Indian trade official who runs Global Trade Research Initiative (GTRI), a Delhi-based think tank.
That uncertainty hinges on a few key flashpoints - none more contentious than agriculture
"There are two real challenges to concluding an initial agreement. First on the list is US access to the Indian market for basic agriculture products. India will need to protect its basic agriculture sector for economic and political reasons," Richard Rossow, who tracks India's economy at Washington's Center for Strategic and International Studies, told the BBC.
For years, Washington has pushed for greater access to India's farm sector, seeing it as a major untapped market. But India has fiercely protected it, citing food security, livelihoods and interests of millions of small farmers
Mr Rossow says the "second issue is India's non-tariff barriers. Issues like India's growing set of 'Quality Control Orders' (QCO) are significant obstacles to US market access and may prove tricky to meaningfully handle in a trade deal".
The US has raised concerns over what it calls India's growing and burdensome import-quality rules. Over 700 QCOs - part of the "self-reliant India" push - aim to curb low-quality imports and promote domestic manufacturing. Suman Berry, a senior member of a government think tank Niti Aayog, has also called these rules a "malign intervention" that restrict imports and raise costs for domestic medium and small scale industries."""
print(x)